// Generated by gencpp from file bunker_msgs/BunkerBmsStatus.msg
// DO NOT EDIT!


#ifndef BUNKER_MSGS_MESSAGE_BUNKERBMSSTATUS_H
#define BUNKER_MSGS_MESSAGE_BUNKERBMSSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bunker_msgs
{
template <class ContainerAllocator>
struct BunkerBmsStatus_
{
  typedef BunkerBmsStatus_<ContainerAllocator> Type;

  BunkerBmsStatus_()
    : SOC(0.0)
    , SOH(0.0)
    , battery_voltage(0.0)
    , battery_current(0.0)
    , battery_temperature(0.0)
    , Alarm_Status_1(0)
    , Alarm_Status_2(0)
    , Warning_Status_1(0)
    , Warning_Status_2(0)  {
    }
  BunkerBmsStatus_(const ContainerAllocator& _alloc)
    : SOC(0.0)
    , SOH(0.0)
    , battery_voltage(0.0)
    , battery_current(0.0)
    , battery_temperature(0.0)
    , Alarm_Status_1(0)
    , Alarm_Status_2(0)
    , Warning_Status_1(0)
    , Warning_Status_2(0)  {
  (void)_alloc;
    }



   typedef double _SOC_type;
  _SOC_type SOC;

   typedef double _SOH_type;
  _SOH_type SOH;

   typedef double _battery_voltage_type;
  _battery_voltage_type battery_voltage;

   typedef double _battery_current_type;
  _battery_current_type battery_current;

   typedef double _battery_temperature_type;
  _battery_temperature_type battery_temperature;

   typedef uint8_t _Alarm_Status_1_type;
  _Alarm_Status_1_type Alarm_Status_1;

   typedef uint8_t _Alarm_Status_2_type;
  _Alarm_Status_2_type Alarm_Status_2;

   typedef uint8_t _Warning_Status_1_type;
  _Warning_Status_1_type Warning_Status_1;

   typedef uint8_t _Warning_Status_2_type;
  _Warning_Status_2_type Warning_Status_2;





  typedef boost::shared_ptr< ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> const> ConstPtr;

}; // struct BunkerBmsStatus_

typedef ::bunker_msgs::BunkerBmsStatus_<std::allocator<void> > BunkerBmsStatus;

typedef boost::shared_ptr< ::bunker_msgs::BunkerBmsStatus > BunkerBmsStatusPtr;
typedef boost::shared_ptr< ::bunker_msgs::BunkerBmsStatus const> BunkerBmsStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator1> & lhs, const ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator2> & rhs)
{
  return lhs.SOC == rhs.SOC &&
    lhs.SOH == rhs.SOH &&
    lhs.battery_voltage == rhs.battery_voltage &&
    lhs.battery_current == rhs.battery_current &&
    lhs.battery_temperature == rhs.battery_temperature &&
    lhs.Alarm_Status_1 == rhs.Alarm_Status_1 &&
    lhs.Alarm_Status_2 == rhs.Alarm_Status_2 &&
    lhs.Warning_Status_1 == rhs.Warning_Status_1 &&
    lhs.Warning_Status_2 == rhs.Warning_Status_2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator1> & lhs, const ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bunker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8825e008639377a676911a7ad9d079ce";
  }

  static const char* value(const ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8825e008639377a6ULL;
  static const uint64_t static_value2 = 0x76911a7ad9d079ceULL;
};

template<class ContainerAllocator>
struct DataType< ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bunker_msgs/BunkerBmsStatus";
  }

  static const char* value(const ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#BMS date\n"
"float64 SOC\n"
"float64 SOH\n"
"float64 battery_voltage\n"
"float64 battery_current\n"
"float64 battery_temperature\n"
"\n"
"#BMS status\n"
"uint8 Alarm_Status_1\n"
"uint8 Alarm_Status_2\n"
"uint8 Warning_Status_1\n"
"uint8 Warning_Status_2\n"
;
  }

  static const char* value(const ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.SOC);
      stream.next(m.SOH);
      stream.next(m.battery_voltage);
      stream.next(m.battery_current);
      stream.next(m.battery_temperature);
      stream.next(m.Alarm_Status_1);
      stream.next(m.Alarm_Status_2);
      stream.next(m.Warning_Status_1);
      stream.next(m.Warning_Status_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BunkerBmsStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bunker_msgs::BunkerBmsStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "SOC: ";
    Printer<double>::stream(s, indent + "  ", v.SOC);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "SOH: ";
    Printer<double>::stream(s, indent + "  ", v.SOH);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "battery_voltage: ";
    Printer<double>::stream(s, indent + "  ", v.battery_voltage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "battery_current: ";
    Printer<double>::stream(s, indent + "  ", v.battery_current);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "battery_temperature: ";
    Printer<double>::stream(s, indent + "  ", v.battery_temperature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Alarm_Status_1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Alarm_Status_1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Alarm_Status_2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Alarm_Status_2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Warning_Status_1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Warning_Status_1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Warning_Status_2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Warning_Status_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BUNKER_MSGS_MESSAGE_BUNKERBMSSTATUS_H
