// Generated by gencpp from file bunker_msgs/BunkerStatus.msg
// DO NOT EDIT!


#ifndef BUNKER_MSGS_MESSAGE_BUNKERSTATUS_H
#define BUNKER_MSGS_MESSAGE_BUNKERSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <bunker_msgs/BunkerMotorState.h>

namespace bunker_msgs
{
template <class ContainerAllocator>
struct BunkerStatus_
{
  typedef BunkerStatus_<ContainerAllocator> Type;

  BunkerStatus_()
    : header()
    , linear_velocity(0.0)
    , angular_velocity(0.0)
    , base_state(0)
    , control_mode(0)
    , fault_code(0)
    , battery_voltage(0.0)
    , motor_states()  {
    }
  BunkerStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , linear_velocity(0.0)
    , angular_velocity(0.0)
    , base_state(0)
    , control_mode(0)
    , fault_code(0)
    , battery_voltage(0.0)
    , motor_states()  {
  (void)_alloc;
      motor_states.assign( ::bunker_msgs::BunkerMotorState_<ContainerAllocator> (_alloc));
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef double _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef uint8_t _base_state_type;
  _base_state_type base_state;

   typedef uint8_t _control_mode_type;
  _control_mode_type control_mode;

   typedef uint16_t _fault_code_type;
  _fault_code_type fault_code;

   typedef double _battery_voltage_type;
  _battery_voltage_type battery_voltage;

   typedef boost::array< ::bunker_msgs::BunkerMotorState_<ContainerAllocator> , 2>  _motor_states_type;
  _motor_states_type motor_states;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(MOTOR_ID_FRONT_RIGHT)
  #undef MOTOR_ID_FRONT_RIGHT
#endif
#if defined(_WIN32) && defined(MOTOR_ID_FRONT_LEFT)
  #undef MOTOR_ID_FRONT_LEFT
#endif
#if defined(_WIN32) && defined(MOTOR_ID_REAR_RIGHT)
  #undef MOTOR_ID_REAR_RIGHT
#endif
#if defined(_WIN32) && defined(MOTOR_ID_REAR_LEFT)
  #undef MOTOR_ID_REAR_LEFT
#endif
#if defined(_WIN32) && defined(LIGHT_ID_FRONT)
  #undef LIGHT_ID_FRONT
#endif
#if defined(_WIN32) && defined(LIGHT_ID_REAR)
  #undef LIGHT_ID_REAR
#endif

  enum {
    MOTOR_ID_FRONT_RIGHT = 0,
    MOTOR_ID_FRONT_LEFT = 1,
    MOTOR_ID_REAR_RIGHT = 2,
    MOTOR_ID_REAR_LEFT = 3,
    LIGHT_ID_FRONT = 0,
    LIGHT_ID_REAR = 1,
  };


  typedef boost::shared_ptr< ::bunker_msgs::BunkerStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bunker_msgs::BunkerStatus_<ContainerAllocator> const> ConstPtr;

}; // struct BunkerStatus_

typedef ::bunker_msgs::BunkerStatus_<std::allocator<void> > BunkerStatus;

typedef boost::shared_ptr< ::bunker_msgs::BunkerStatus > BunkerStatusPtr;
typedef boost::shared_ptr< ::bunker_msgs::BunkerStatus const> BunkerStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bunker_msgs::BunkerStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bunker_msgs::BunkerStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bunker_msgs::BunkerStatus_<ContainerAllocator1> & lhs, const ::bunker_msgs::BunkerStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.linear_velocity == rhs.linear_velocity &&
    lhs.angular_velocity == rhs.angular_velocity &&
    lhs.base_state == rhs.base_state &&
    lhs.control_mode == rhs.control_mode &&
    lhs.fault_code == rhs.fault_code &&
    lhs.battery_voltage == rhs.battery_voltage &&
    lhs.motor_states == rhs.motor_states;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bunker_msgs::BunkerStatus_<ContainerAllocator1> & lhs, const ::bunker_msgs::BunkerStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bunker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bunker_msgs::BunkerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bunker_msgs::BunkerStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bunker_msgs::BunkerStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bunker_msgs::BunkerStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bunker_msgs::BunkerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bunker_msgs::BunkerStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bunker_msgs::BunkerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a86f055b47966ef7079cc8ff92ba8758";
  }

  static const char* value(const ::bunker_msgs::BunkerStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa86f055b47966ef7ULL;
  static const uint64_t static_value2 = 0x079cc8ff92ba8758ULL;
};

template<class ContainerAllocator>
struct DataType< ::bunker_msgs::BunkerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bunker_msgs/BunkerStatus";
  }

  static const char* value(const ::bunker_msgs::BunkerStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bunker_msgs::BunkerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int8 MOTOR_ID_FRONT_RIGHT = 0\n"
"int8 MOTOR_ID_FRONT_LEFT = 1\n"
"int8 MOTOR_ID_REAR_RIGHT = 2\n"
"int8 MOTOR_ID_REAR_LEFT = 3\n"
"\n"
"int8 LIGHT_ID_FRONT = 0\n"
"int8 LIGHT_ID_REAR = 1\n"
"\n"
"# motion state\n"
"float64 linear_velocity\n"
"float64 angular_velocity\n"
"\n"
"# base state\n"
"uint8 base_state\n"
"uint8 control_mode\n"
"uint16 fault_code\n"
"float64 battery_voltage\n"
"\n"
"# motor state\n"
"BunkerMotorState[2] motor_states\n"
"\n"
"# light state\n"
"#bool light_control_enabled\n"
"#BunkerLightState front_light_state\n"
"#BunkerLightState rear_light_state\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: bunker_msgs/BunkerMotorState\n"
"float64 current\n"
"float64 rpm\n"
"float64 temperature\n"
;
  }

  static const char* value(const ::bunker_msgs::BunkerStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bunker_msgs::BunkerStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.linear_velocity);
      stream.next(m.angular_velocity);
      stream.next(m.base_state);
      stream.next(m.control_mode);
      stream.next(m.fault_code);
      stream.next(m.battery_voltage);
      stream.next(m.motor_states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BunkerStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bunker_msgs::BunkerStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bunker_msgs::BunkerStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.linear_velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angular_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.angular_velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "base_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.base_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "control_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fault_code: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.fault_code);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "battery_voltage: ";
    Printer<double>::stream(s, indent + "  ", v.battery_voltage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "motor_states: ";
    if (v.motor_states.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.motor_states.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::bunker_msgs::BunkerMotorState_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.motor_states[i]);
    }
    if (v.motor_states.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // BUNKER_MSGS_MESSAGE_BUNKERSTATUS_H
