// Generated by gencpp from file yesense_imu/YesenseImuQuaternion.msg
// DO NOT EDIT!


#ifndef YESENSE_IMU_MESSAGE_YESENSEIMUQUATERNION_H
#define YESENSE_IMU_MESSAGE_YESENSEIMUQUATERNION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yesense_imu
{
template <class ContainerAllocator>
struct YesenseImuQuaternion_
{
  typedef YesenseImuQuaternion_<ContainerAllocator> Type;

  YesenseImuQuaternion_()
    : q0(0.0)
    , q1(0.0)
    , q2(0.0)
    , q3(0.0)  {
    }
  YesenseImuQuaternion_(const ContainerAllocator& _alloc)
    : q0(0.0)
    , q1(0.0)
    , q2(0.0)
    , q3(0.0)  {
  (void)_alloc;
    }



   typedef float _q0_type;
  _q0_type q0;

   typedef float _q1_type;
  _q1_type q1;

   typedef float _q2_type;
  _q2_type q2;

   typedef float _q3_type;
  _q3_type q3;





  typedef boost::shared_ptr< ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> const> ConstPtr;

}; // struct YesenseImuQuaternion_

typedef ::yesense_imu::YesenseImuQuaternion_<std::allocator<void> > YesenseImuQuaternion;

typedef boost::shared_ptr< ::yesense_imu::YesenseImuQuaternion > YesenseImuQuaternionPtr;
typedef boost::shared_ptr< ::yesense_imu::YesenseImuQuaternion const> YesenseImuQuaternionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator1> & lhs, const ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator2> & rhs)
{
  return lhs.q0 == rhs.q0 &&
    lhs.q1 == rhs.q1 &&
    lhs.q2 == rhs.q2 &&
    lhs.q3 == rhs.q3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator1> & lhs, const ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yesense_imu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63ca77594d1bad6ed3441f10f9332674";
  }

  static const char* value(const ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63ca77594d1bad6eULL;
  static const uint64_t static_value2 = 0xd3441f10f9332674ULL;
};

template<class ContainerAllocator>
struct DataType< ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yesense_imu/YesenseImuQuaternion";
  }

  static const char* value(const ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 q0\n"
"float32 q1\n"
"float32 q2\n"
"float32 q3\n"
;
  }

  static const char* value(const ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q0);
      stream.next(m.q1);
      stream.next(m.q2);
      stream.next(m.q3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YesenseImuQuaternion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yesense_imu::YesenseImuQuaternion_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "q0: ";
    Printer<float>::stream(s, indent + "  ", v.q0);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "q1: ";
    Printer<float>::stream(s, indent + "  ", v.q1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "q2: ";
    Printer<float>::stream(s, indent + "  ", v.q2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "q3: ";
    Printer<float>::stream(s, indent + "  ", v.q3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YESENSE_IMU_MESSAGE_YESENSEIMUQUATERNION_H
