// Generated by gencpp from file yesense_imu/YesenseImuLocation.msg
// DO NOT EDIT!


#ifndef YESENSE_IMU_MESSAGE_YESENSEIMULOCATION_H
#define YESENSE_IMU_MESSAGE_YESENSEIMULOCATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yesense_imu
{
template <class ContainerAllocator>
struct YesenseImuLocation_
{
  typedef YesenseImuLocation_<ContainerAllocator> Type;

  YesenseImuLocation_()
    : longtidue(0.0)
    , latitude(0.0)
    , altidue(0.0)  {
    }
  YesenseImuLocation_(const ContainerAllocator& _alloc)
    : longtidue(0.0)
    , latitude(0.0)
    , altidue(0.0)  {
  (void)_alloc;
    }



   typedef double _longtidue_type;
  _longtidue_type longtidue;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef float _altidue_type;
  _altidue_type altidue;





  typedef boost::shared_ptr< ::yesense_imu::YesenseImuLocation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yesense_imu::YesenseImuLocation_<ContainerAllocator> const> ConstPtr;

}; // struct YesenseImuLocation_

typedef ::yesense_imu::YesenseImuLocation_<std::allocator<void> > YesenseImuLocation;

typedef boost::shared_ptr< ::yesense_imu::YesenseImuLocation > YesenseImuLocationPtr;
typedef boost::shared_ptr< ::yesense_imu::YesenseImuLocation const> YesenseImuLocationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yesense_imu::YesenseImuLocation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yesense_imu::YesenseImuLocation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yesense_imu::YesenseImuLocation_<ContainerAllocator1> & lhs, const ::yesense_imu::YesenseImuLocation_<ContainerAllocator2> & rhs)
{
  return lhs.longtidue == rhs.longtidue &&
    lhs.latitude == rhs.latitude &&
    lhs.altidue == rhs.altidue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yesense_imu::YesenseImuLocation_<ContainerAllocator1> & lhs, const ::yesense_imu::YesenseImuLocation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yesense_imu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yesense_imu::YesenseImuLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yesense_imu::YesenseImuLocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yesense_imu::YesenseImuLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yesense_imu::YesenseImuLocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yesense_imu::YesenseImuLocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yesense_imu::YesenseImuLocation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yesense_imu::YesenseImuLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cf93867aa740e2448c799a9da22809d";
  }

  static const char* value(const ::yesense_imu::YesenseImuLocation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cf93867aa740e24ULL;
  static const uint64_t static_value2 = 0x48c799a9da22809dULL;
};

template<class ContainerAllocator>
struct DataType< ::yesense_imu::YesenseImuLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yesense_imu/YesenseImuLocation";
  }

  static const char* value(const ::yesense_imu::YesenseImuLocation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yesense_imu::YesenseImuLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 longtidue\n"
"float64 latitude\n"
"float32 altidue\n"
;
  }

  static const char* value(const ::yesense_imu::YesenseImuLocation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yesense_imu::YesenseImuLocation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.longtidue);
      stream.next(m.latitude);
      stream.next(m.altidue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YesenseImuLocation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yesense_imu::YesenseImuLocation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yesense_imu::YesenseImuLocation_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "longtidue: ";
    Printer<double>::stream(s, indent + "  ", v.longtidue);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "altidue: ";
    Printer<float>::stream(s, indent + "  ", v.altidue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YESENSE_IMU_MESSAGE_YESENSEIMULOCATION_H
