// Generated by gencpp from file yesense_imu/YesenseImuVelocity.msg
// DO NOT EDIT!


#ifndef YESENSE_IMU_MESSAGE_YESENSEIMUVELOCITY_H
#define YESENSE_IMU_MESSAGE_YESENSEIMUVELOCITY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yesense_imu
{
template <class ContainerAllocator>
struct YesenseImuVelocity_
{
  typedef YesenseImuVelocity_<ContainerAllocator> Type;

  YesenseImuVelocity_()
    : v_e(0.0)
    , v_n(0.0)
    , v_u(0.0)  {
    }
  YesenseImuVelocity_(const ContainerAllocator& _alloc)
    : v_e(0.0)
    , v_n(0.0)
    , v_u(0.0)  {
  (void)_alloc;
    }



   typedef float _v_e_type;
  _v_e_type v_e;

   typedef float _v_n_type;
  _v_n_type v_n;

   typedef float _v_u_type;
  _v_u_type v_u;





  typedef boost::shared_ptr< ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct YesenseImuVelocity_

typedef ::yesense_imu::YesenseImuVelocity_<std::allocator<void> > YesenseImuVelocity;

typedef boost::shared_ptr< ::yesense_imu::YesenseImuVelocity > YesenseImuVelocityPtr;
typedef boost::shared_ptr< ::yesense_imu::YesenseImuVelocity const> YesenseImuVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yesense_imu::YesenseImuVelocity_<ContainerAllocator1> & lhs, const ::yesense_imu::YesenseImuVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.v_e == rhs.v_e &&
    lhs.v_n == rhs.v_n &&
    lhs.v_u == rhs.v_u;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yesense_imu::YesenseImuVelocity_<ContainerAllocator1> & lhs, const ::yesense_imu::YesenseImuVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yesense_imu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee3bc63430d946c96d8af696d4656826";
  }

  static const char* value(const ::yesense_imu::YesenseImuVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee3bc63430d946c9ULL;
  static const uint64_t static_value2 = 0x6d8af696d4656826ULL;
};

template<class ContainerAllocator>
struct DataType< ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yesense_imu/YesenseImuVelocity";
  }

  static const char* value(const ::yesense_imu::YesenseImuVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 v_e\n"
"float32 v_n\n"
"float32 v_u\n"
;
  }

  static const char* value(const ::yesense_imu::YesenseImuVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v_e);
      stream.next(m.v_n);
      stream.next(m.v_u);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YesenseImuVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yesense_imu::YesenseImuVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yesense_imu::YesenseImuVelocity_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "v_e: ";
    Printer<float>::stream(s, indent + "  ", v.v_e);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v_n: ";
    Printer<float>::stream(s, indent + "  ", v.v_n);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v_u: ";
    Printer<float>::stream(s, indent + "  ", v.v_u);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YESENSE_IMU_MESSAGE_YESENSEIMUVELOCITY_H
